name: Auto Generate Blog

on:
 schedule:
  - cron: "0 1 * * *"   # pagi
  - cron: "0 10 * * *"  # sore

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install || true

      - name: Generate articles
        run: npm run generate

      - name: Update index & category
        run: npm run update

      - name: Generate sitemap
        run: npm run sitemap

      - name: Commit & push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto update blog & sitemap" || echo "No changes"
          git push

